# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
---
version: 2
jobs:
  Moon:
    macos:
        xcode: "10.0.0"
    working_directory: ~/Waves/iOS
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: waves_test
    shell: /bin/bash --login -eo pipefail
    steps:
      - add_ssh_keys:
          fingerprints:
            - "43:eb:59:d6:49:f1:ae:81:cb:5a:ba:b8:01:64:19:39"
      - checkout
      - restore_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}      
      - run:
          name: Show exported variables
          command: export
      - run:
          name: SSH
          command: ls -la ~/.ssh/
      - run:
          name: SSH Cat config
          command: cat ~/.ssh/config
      - run: 
          name: Test ouput
          command: mkdir -p $FL_OUTPUT_DIR && touch $FL_OUTPUT_DIR/test_4.txt
      - run:
          name: Bundle
          command: bundle check || bundle install --path vendor/bundle
      - save_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle            
      - run:
          name: Fastlane Build
          command: bundle exec fastlane $FASTLANE_LANE --verbose
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan
  X61:
    macos:
        xcode: "10.0.0"
    working_directory: ~/Waves/iOS
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: waves
    shell: /bin/bash --login -eo pipefail
    steps:
      - add_ssh_keys:
          fingerprints:
            - "43:eb:59:d6:49:f1:ae:81:cb:5a:ba:b8:01:64:19:39"
      - checkout
      - restore_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}      
      - run:
          name: SSH
          command: ls -la ~/.ssh/
      - run:
          name: SSH Cat config
          command: cat ~/.ssh/config      
      - run: 
          name: Test ouput
          command: mkdir -p $FL_OUTPUT_DIR && touch $FL_OUTPUT_DIR/test_4.txt
      - run:
          name: Bundle
          command: bundle check || bundle install --path vendor/bundle
      - save_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle            
      - run:
          name: Fastlane Build
          command: bundle exec fastlane $FASTLANE_LANE --verbose
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan
workflows:
  version: 2
  Spaceship:
    jobs:
      - Moon:
          filters:
            branches:
              only: develop
      - X61:
          filters:
            branches:
              only: release/v2.0rc0
